doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                dbname: main_local
                host: 127.0.0.1
                port: 3306
                user: root
                password: password
                driver: pdo_mysql
                server_version: 'mariadb-10.4.12'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: false
        mappings:
            Auth:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Auth/Entity'
                prefix: 'App\Domain\Auth\Entity'
                alias: Auth
